name: Publish Extension

# Controls when the workflow will run
on:
  # Triggers the workflow on push events.
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Uncomment this if you want to debug Github action using SSH.
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Build Deployable App
        run: |
         npm ci --ignore-scripts
         npm run build-zip

         echo "Listing files..."
         ls -la

      # - name: Chrome Extension upload & publish
      #   uses: Passiverecords/chrome-extension-upload-action@1.4.1
      #   with:
      #     refresh-token: ${{ secrets.REFRESH_TOKEN }}
      #     client-id: ${{ secrets.CLIENT_ID }}
      #     client-secret: ${{ secrets.CLIENT_SECRET }}
      #     file-name: './build.zip'
      #     app-id: 'xyz' # get app id from Web Store once extension is published
      #     publish: true
